@startuml Discuenta Class Diagram

package "shared" {
   package "components" {

   }

   package "model" {
       class "Error" <<Entity>> {

       }
   }
}

package "receivables" {
    package "components" {

    }

    package "model" {
        entity "Document" <<Entity>> {

        }

        class "DocumentType" <<Value Object>> {
            - #VALID_TYPES: Map<string, string>
            - #type: string
            + constructor(value: string)
            + get value(): string
            + equals(other: DocumentType): boolean
        }

        class "DocumentStatus" <<Value Object>> {
            - #VALID_STATUSES: Map<string, string>
            - #status: string
            + constructor(status: string)
            + get status(): string
            + equals(other: DocumentStatus): boolean
        }
    }

    package "pages" {

    }

    package "services" {

    }
}

'Relationship
receivables.model.Document --> shared.model.Error : uses
@enduml